---
- name: Cau hinh Switch
  hosts: all
  gather_facts: no 

  tasks:
    - name: show ip 
      ios_command:
        commands: show ip int bri
      
      register: output

    - debug: var=output.stdout_lines
